### Spectral embedding : intuition
----

In [5]:
import numpy as np

#### Break up a sequence into subsequences

In [1]:
def get_kmers(sequence, kmer_size=3):
    return [sequence[i: i+kmer_size] for i in range(len(sequence) - kmer_size + 1)]

In [2]:
kmer_size = 3
sequence = 'AAGGATT'
get_kmers(sequence, kmer_size=kmer_size)

['AAG', 'AGG', 'GGA', 'GAT', 'ATT']

#### Assign an index to subsequences

In [ ]:
index of 'AAG':
    4**0 * index(first letter'A') +
    4**1 * index(second letter'A') +
    4**2 * index(third letter 'G')

#### Like binary code:

In [ ]:
index('1001') = 9

  =  2**3 * index(first number '1') +
     2**2 * index(second letter '0') +
     2**1 * index(third letter '0') + 
     2**0 * index(fourth letter '1')

In [3]:
def base2int(c):
    return {'A': 0, 'C': 1, 'G': 2, 'T': 3}.get(c, 0)

def index(kmer):
    # Transform the kmer into sequence of character indices
    return [base2int(c) for c in kmer]

In [7]:
kmer = 'GAA'
base_indices = np.array([base2int(base) for base in kmer])
base_indices

array([2, 0, 0])

In [8]:
multiplier = 4 ** np.arange(len(kmer))
multiplier

array([ 1,  4, 16])

In [10]:
kmer_index = multiplier[::-1].dot(base_indices)
kmer_index

32

In [11]:
kmer_one_hot = np.zeros(4**kmer_size).astype(int)
kmer_one_hot[kmer_index] += 1

In [12]:
kmer_one_hot

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
def spectral_embedding(sequence):
    kmers = get_kmers(sequence)
    multiplier = 4 ** np.arange(len(kmer))[::-1]
    kmer_indices = [multiplier.dot(index(kmer)) for kmer in kmers]
    one_hot_vector = np.zeros(4**kmer_size).astype(int)
    for kmer_index in kmer_indices:
        one_hot_vector[kmer_index] += 1
    return one_hot_vector

In [16]:
sequence = 'GAAAA'
spectral_embedding(sequence)

array([2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
spectral_embedding(sequence) / (len(sequence)-kmer_size+1)

array([0.66666667, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.33333333, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

#### Spectral embedding for DNA, k=3
- first coordinate: number of times `AAA` appears in sequence
- second coordinate: number of times `CAA` appears in sequence
- third coordinate: number of times `GAA` appears in sequence
-   .
-   .
-   .
- last coordinate: number of times `TTT` appears in sequence

#### Watch out!
For large $k$, the vectors will be very large (k=10, then 4**k = 1million elements in the vector)

#### $\to$ Use sparse vectors
`scipy.sparse`

In [ ]:
suppose you have two kernels k1 and k2 that work on strings

In [ ]:
convolution kernel k = k1 * k2

In [ ]:
k('ACG') = k1('')k2('ACG') + k1('A')k2('CG') + k1('AC')k2('G') + k1('ACA')k2('')